### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by davesteinberg** [ibm-garage-cloud/ibm-garage-developer-guide#10]
I'm seeing lots of broken links in the developer guide.

From the MOOC Homework page...

* Validate: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/homework/teams  
* Part 1 Exercise: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/practical/inventory-part1

From the left-side navigation pane...

Starter Kit Templates
* Overview: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/starterkits/overview
* Templates: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/starterkits/starterkittemplates

Programming Guide
* Databases: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/programming/databases
* Securing Applications: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/programming/security

Practical Guides
* Overview: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/practical/overview
* Inventory Micro App - Part 1: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/practical/inventory-part1

Administrator Guide
* Install into existing cluster: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/installation-existing
* Install into Red Hat CodeReady: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/installation-crc
* Artifactory Setup: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/artifactory-setup
* ArgoCD Setup: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/argocd-setup
* Infrastructure as Code: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/iasc
* Cluster configuration: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/cluster-configuration
* Destroying: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/admin/destroying

I cloned the code to try to have a look, but I don't know Gatsby, and `npm run dev` fails:

```
$ npm run dev

> ibm-garage-developer-guide@1.0.0 dev /Users/dave/code/garage/catalyst/ibm-garage-developer-guide
> gatsby develop

The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

No idea if this is related or not. I see there are Markdown files for at least some of the pages that are the targets of broken links, but I don't know how they're meant to be hooked up.

**Comment by davesteinberg** [comment]
Hmm...interesting. The links work from here, but not client-side from within the docs. I'm seeing errors like this in the console:

webpack-runtime-e21050775afadc0d5cfd.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 34 failed.
(error: https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/component---src-pages-homework-teams-index-mdx-4380b1f622cfdc71c989.js)
    at Function.a.e (https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/webpack-runtime-e21050775afadc0d5cfd.js:1:4504)
    at Object.component---src-pages-homework-teams-index-mdx (https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/app-4ba8544e6a609ea38f1a.js:1:1925285)
    at n.loadComponent (https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/app-4ba8544e6a609ea38f1a.js:1:1667064)
    at https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/app-4ba8544e6a609ea38f1a.js:1:1664922

**Comment by mjperrins** [comment]
When running locally the git pages prefix is in the links , we discovered this late when created the docs for MOOC , we will investigate how to make this dynamic so works in local and published mode

**Comment by mjperrins** [comment]
We have been doing some work on the broken links so they are at least working on the server copy, we are reaching out to the Gatasby team to see if there is a simple way of setting this up

**Comment by seansund** [comment]
Is this still an issue? It seems like all the links are working now on the published site and I can access the site when I run `npm run dev` as well

**Comment by davesteinberg** [comment]
@seansund It looks to me like these problems are now resolved.
