### ISSUE TITLE
Cloudant Binding Secret missing from individual namespaces

### ISSUE THREAD

**Issue by osowski** [ibm-garage-cloud/ibm-garage-developer-guide#25]
When integrating Cloudant into the Inventory app, the required `binding-mooc-one-rhos-cloudant` Secret is missing from the individual user's namespace and only defined in the main `dev` namespace. 

By the time users hit https://github.com/ibm-garage-cloud/ibm-garage-developer-guide/blob/master/src/pages/practical/inventory-part2/index.mdx#update-the-configuration-values-in-the-valuesyaml-helm-chart, they would expect the necessary Secrets to exist in the correct namespace for association with the Deployments in the Helm chart.

This may be something that needs to be added to the `igc` tooling, however I was able to copy over the Secret into my `dev-reo` namespace with the following command and successfully proceed:
`oc get secrets -n dev -o json binding-mooc-one-rhos-cloudant | jq '.metadata.namespace="dev-reo"' | oc apply -f -`

**Comment by mjperrins** [comment]
I know @seansund is working on this, will get back to you with a fix

**Comment by mjperrins** [comment]
I believe the documentation is now been updated and is being published as we speak so we can close this issue
