### ISSUE TITLE
Maureen needs the ability to select the Terraform Modules I want to create a Private Catalog with IBM Cloud

### ISSUE THREAD

**Issue by mjperrins** [ibm-garage-cloud/ibm-garage-developer-guide#63]
As a developer I need the ability to select the Terraform Modules I want to create a Private Catalog with IBM Cloud

- [ ] Map Terraform Stages into YAML and store that at root of iteration zero repository
- [ ] Add new command `igc private-catalog-builder` | `igc pcb` to `igc` CLI 
- [ ] Add functionality to read YAML and present a CLI user experience based on inquirer npm package
- [ ] Allow Stages to be selected and added to the a private catalog directory, reading stages from git repo
- [ ] Enable selections of its module and its dependencies
- [ ] Allow forced selection of CI technologies and Artifact technologies give select one or there other
- [ ] Add Private catalog metadata to the directory
- [ ] Zip up directory and allow it to be registered to the Private Catalog API
- [ ] Test with installation into Kubernetes and OpenShift cluster types
- [ ] Test combinations of stages

Matthew Perrins:palm_tree: 11:42
is there a reference for the yaml files you create ? for Garage engagements we want to turn up with a set of Private Catalog assets and then register them , to cut down the time it takes to get a team delivering content and MVPs for a client and to show the separation of the roles for a system admin,

but its fine we can wait for that CLI support hopefully next year

Gili Mendel:palm_tree: 11:56
I think that the best bet for you, is to import a helm chart, and use the API https://cm.globalcatalog.test.cloud.ibm.com/api to  get it with a reference data.   You can then create an offering with curl

Use the UI to import helm: https://dev.console.test.cloud.ibm.com/content-mgmt

**Comment by seansund** [comment]
Issue moved to [ibm-garage-cloud/planning #224](https://github.com/ibm-garage-cloud/planning/issues/224) via [**ZenHub**](https://www.zenhub.com/)
