### ISSUE TITLE
page isn't readable with chrome

### ISSUE THREAD

**Issue by sam-github** [ibm-garage-cloud/ibm-garage-developer-guide#82]
**Describe the bug**
ibm-garage-cloud.github.io/ibm-garage-developer-guide/starterkits/starterkittemplates is unreadable

https://ibm-garage-cloud.github.io/ibm-garage-developer-guide/starterkits/starterkittemplates/ with chrome looks like this:

![image](https://user-images.githubusercontent.com/17607/75196118-2af4c900-5710-11ea-94f9-e6f713103cc2.png)

Its not possible to move the left-side navigation panel, and its not possible to scroll the text, so the left 1/3 of the page can't be read.

In Firefox, its readable.

![image](https://user-images.githubusercontent.com/17607/75196186-5677b380-5710-11ea-846d-5e569fe0f2a6.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] current

**Smartphone (please complete the following information):**

**Additional context**

**Comment by csantanapr** [comment]
works for me on chrome
https://cloudnativetoolkit.dev/codepatterns/gitrepos

![image](https://user-images.githubusercontent.com/1094878/79614373-638c9f80-80ce-11ea-8bcf-1fa801bc329c.png)

**Comment by sam-github** [comment]
Yep, works for me now, too.
